name: c4bank-from-remote-image

services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    container_name: 'zookeeper-from-remote-image'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2183
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2183:2183'
    volumes:
      - zookeeper_data_vol:/var/lib/zookeeper/data
      - zookeeper_log_vol:/var/lib/zookeeper/log
      - zookeeper_secrets_vol:/etc/zookeeper/secrets

  kafka:
    image: 'confluentinc/cp-kafka:latest'
    container_name: 'kafka-from-remote-image'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2183
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - '9094:9094'
    volumes:
      - kafka_vol:/var/lib/kafka/data
      - kafka_vol:/var/lib/kafka/log
      - kafka_vol:/etc/kafka/secrets

  c4bank:
    container_name: 'c4bank-jar-from-remote-image'
    image: 'mendesco/c4bank:0.0.1'
    ports:
      - '7000:7000'
    depends_on:
      - kafka
    environment:
      SERVER_PORT: 7000
      KAFKA_PORT: 9094
      KAFKA_URL: localhost
      ZOOKEEPER_PORT: 2183

volumes:
  zookeeper_data_vol:
  zookeeper_log_vol:
  zookeeper_secrets_vol:
  kafka_vol: